db:
  mysql:
    type: mysql
    host: 127.0.0.1
    port: 3306

app:
  host: 127.0.0.1
  port: 8000
  log_on: true
  session_secret: tl-bright
  jwt_secret: bright
  token_expires: 1d
  refresh_token_expires: 2d
